BloodBankProject.MVC/Controllers/DonationsController.cs
using BloodBankProject.BLL.Managers.DonationManager;
using BloodBankProject.BLL.ViewModels.DonationViewModel;
using BloodBankProject.BLL.ViewModels.DonorViewModel;
using BloodBankProject.DAL.Data.Models;
using BloodBankProject.DAL.Repositories.EmailReposirory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BloodBankProject.MVC.Controllers
{
    [Authorize]
    public class DonationsController : Controller
    {
        private readonly IDonationManager _donationManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailRepo _emailRepo;

        public DonationsController(IDonationManager donationManager, UserManager<ApplicationUser> userManager,IEmailRepo emailRepo)
        {
            _donationManager = donationManager;
            _userManager = userManager;
            _emailRepo = emailRepo;
        }


        public async Task<IActionResult> Register()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Accounts"); 
            }


            var donationRegisterVM = new DonationRegisterWithChildVM
            {
                BloodStockAddVM = new BLL.ViewModels.BloodStockViewModel.BloodStockAddVM
                {
                    AvailableQuantity = 1
                },
                DonorRegisterWithParentVM = new DonorRegisterWithParentVM
                {
                    City = user.City,
                    Email = user.Email,
                    LastDonationDate = user.LastDonationDate
                }
            };

            return View(donationRegisterVM);
        }

        [HttpPost]
        public async Task<IActionResult> Register(DonationRegisterWithChildVM donationRegisterWithChildVM)
        {
            if (!ModelState.IsValid)
            {
                return View(donationRegisterWithChildVM);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Accounts");
            }

            
            if (donationRegisterWithChildVM.DonationDate != default(DateTime))
            {
                donationRegisterWithChildVM.ExpirationDate = donationRegisterWithChildVM.DonationDate.AddYears(1);
            }

            
            var result = _donationManager.Add(donationRegisterWithChildVM, user.Email); 

            if (result.IsSuccess)
            {
                TempData["Message"] = "Donation request submitted!";
                return RedirectToAction("MyDetails", "Accounts");
            }
            else
            {
                await _emailRepo.SendEmailAsync(user.Email, "Donation Request Status", result.ErrorMessage);
                TempData["Message"] = "There was a problem with your donation. Please check the form and try again.";

            }

            return View(donationRegisterWithChildVM);
        }

    }
}

BloodBankProject.MVC/Controllers/RequestController.cs
using BloodBankProject.BLL.Managers.HospitalManager;
using BloodBankProject.BLL.Managers.RequestManager;
using BloodBankProject.BLL.ViewModels.HospitalViewModels;
using BloodBankProject.BLL.ViewModels.RequestViewModels;
using BloodBankProject.DAL.Data.Models;
using BloodBankProject.DAL.Repositories.HospitalRepository;
using Microsoft.AspNetCore.Mvc;

namespace BloodBankProject.MVC.Controllers
{
    public class RequestController : Controller
    {
        private readonly IRequestManager _requestManager;
        private readonly IHospitalRepo _hospitalRepo;

        public RequestController(IRequestManager requestManager,IHospitalRepo hospitalRepo)
        {
              _requestManager = requestManager;
            _hospitalRepo = hospitalRepo;
        }
        //Request/GetAll
        public IActionResult GetAll()
        {
          
            var AllRequests = _requestManager.GetAll();
            return View(AllRequests);
        }

       //Request/Add
        public IActionResult Add()
        {
            var model = new RequestAddVM
            {
                HospitalReadVMs = _hospitalRepo.GetAll().Select(h => new HospitalReadVM
                {
                    Id = h.Id,
                    Name = h.Name,
                    City = h.City
                })
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(RequestAddVM requestAddVM)
        {
            if (!ModelState.IsValid)
            {
                return View(requestAddVM);
            }

            _requestManager.Add(requestAddVM);

           
            var availableBlood = _requestManager.GetAvailableBlood(requestAddVM);


            //BloodStocks/GetAll
            return RedirectToAction("GetAll", "BloodStocks");
           
        }
    }
}

BloodBankProject.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BloodBankProject.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BloodBankProject.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BloodBankProject.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Accounts" asp-action="MyDetails">My Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Donations" asp-action="Register">My Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BloodBankProject.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BloodBankProject.MVC/Views/Shared/_WebLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Blood Bank</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="/assets/img/favicon.png" rel="icon">
    <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="/assets/css/main.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Bootslander
    * Template URL: https://bootstrapmade.com/bootslander-free-bootstrap-landing-page-template/
    * Updated: Aug 07 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="index-page">

    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="/assets/img/logo.png" alt=""> -->
                <h1 class="sitename">Blood Bank</h1>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="#hero" class="active">Home</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Accounts" asp-action="MyDetails">MyDetails</a></li>
                        <li><a asp-controller="Donations" asp-action="Register">Register Donations</a></li>
                        <li><a asp-controller="BloodStocks" asp-action="GetAll">All Blood Stocks</a></li>
                        <li><a asp-controller="Accounts" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Accounts" asp-action="Login">Login</a></li>
                        <li><a asp-controller="Accounts" asp-action="Register">Register</a></li>
                        <li><a asp-controller="Request" asp-action="Add">Hospital Request</a></li>
                        <li><a asp-controller="Request" asp-action="GetAll">All Requests</a></li>
                    }
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

        </div>
    </header>

    <main class="main">

       
        <section id="hero" class="hero section dark-background">
           
            <div class="container">
                <div class="row gy-4 justify-content-between">
                    <div class="col-lg-4 order-lg-last hero-img" data-aos="zoom-out" data-aos-delay="100">
                        <img src="/assets/img/blood-transfusion.png" class="img-fluid animated" >
                    </div>
                    <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-in">
                        <h1>Save Lives with <span>Blood Stock Management</span></h1>
                        <p>Efficiently manage blood donations and inventory to ensure a stable supply for those in need.</p>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <div class="login-form mt-4">
                                <h4>Login to Get Started</h4>
                                <a asp-controller="Accounts" asp-action="Login" class="btn btn-primary">Login</a>
                                <p class="mt-2">New user? <a asp-controller="Accounts" asp-action="Register">Register here</a></p>
                            </div>
                        }
                        else
                        {
                            <div class="d-flex">
                                <a href="#about" class="btn btn-primary btn-lg">Get Started</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none">
                <defs>
                    <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
                </defs>
                <g class="wave1">
                    <use xlink:href="#wave-path" x="50" y="3"></use>
                </g>
                <g class="wave2">
                    <use xlink:href="#wave-path" x="50" y="0"></use>
                </g>
                <g class="wave3">
                    <use xlink:href="#wave-path" x="50" y="9"></use>
                </g>
            </svg>
        </section>
        <!-- About Section -->
        <section id="about" class="about section">
            <div class="container">
           @RenderBody()
            </div>
        </section><!-- /About Section -->
     

    </main>

    <footer id="footer" class="footer dark-background">

        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-4 col-md-6 footer-about">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <span class="sitename">Bootslander</span>
                    </a>
                    <div class="footer-contact pt-3">
                        <p>A108 Adam Street</p>
                        <p>New York, NY 535022</p>
                        <p class="mt-3"><strong>Phone:</strong> <span>+1 5589 55488 55</span></p>
                        <p><strong>Email:</strong> <span>info@example.com</span></p>
                    </div>
                    <div class="social-links d-flex mt-4">
                        <a href=""><i class="bi bi-twitter-x"></i></a>
                        <a href=""><i class="bi bi-facebook"></i></a>
                        <a href=""><i class="bi bi-instagram"></i></a>
                        <a href=""><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-md-3 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Terms of service</a></li>
                        <li><a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-md-3 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Web Development</a></li>
                        <li><a href="#">Product Management</a></li>
                        <li><a href="#">Marketing</a></li>
                        <li><a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-12 footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
                    <form action="forms/newsletter.php" method="post" class="php-email-form">
                        <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your subscription request has been sent. Thank you!</div>
                    </form>
                </div>

            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© <span>Copyright</span> <strong class="px-1 sitename">Bootslander</strong> <span>All Rights Reserved</span></p>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you've purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>

    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/php-email-form/validate.js"></script>
    <script src="/assets/vendor/aos/aos.js"></script>
    <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="/assets/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>